package com.simple.lightnote.db;

import com.simple.lightnote.model.SimpleNote;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig minimalEntityDaoConfig;

    private final NoteDao noteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        minimalEntityDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        minimalEntityDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(minimalEntityDaoConfig, this);

        registerDao(SimpleNote.class, noteDao);
    }

    public void clear() {
        minimalEntityDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}